const FIELD_INFO = {
  "received": ["Server handoff", "A mail server's record of receiving the message. Read all Received entries from bottom to top to reconstruct the journey.", "Routing"],
  "authentication-results": ["Authentication verdicts", "The receiving provider's combined SPF, DKIM, DMARC, and other trust-check results.", "Authentication"],
  "authentication-results-original": ["Earlier authentication verdicts", "Authentication results recorded before a later gateway or forwarding step changed the message's context.", "Authentication"],
  "arc-authentication-results": ["Forwarding trust evidence", "Authentication results preserved in an ARC chain so later systems can see what an earlier trusted server observed.", "Authentication"],
  "received-spf": ["SPF check detail", "Explains whether the connecting server's IP address was authorized to send mail for the envelope sender's domain.", "Authentication"],
  "dkim-signature": ["Cryptographic sender signature", "A domain-backed signature used to detect changes and establish which domain took responsibility for the message.", "Authentication"],
  "arc-seal": ["Forwarding chain seal", "A tamper-evident seal added by a forwarding service. ARC helps preserve trust checks across intermediaries.", "Authentication"],
  "arc-message-signature": ["Forwarded message signature", "A signature covering selected message headers as part of the ARC forwarding chain.", "Authentication"],
  "from": ["Visible sender", "The name and address shown to the recipient as the message sender. This can differ from the technical Return-Path.", "Identity"],
  "to": ["Visible recipient", "The address displayed as the intended recipient of the message.", "Identity"],
  "return-path": ["Bounce address", "The technical envelope sender used for delivery failures and SPF evaluation. It may legitimately differ from From.", "Identity"],
  "subject": ["Message subject", "The subject line shown in the recipient's inbox.", "Message"],
  "date": ["Sender timestamp", "The date and time claimed by the sending mail client. Server timestamps are stronger evidence of actual timing.", "Message"],
  "message-id": ["Unique message identifier", "An identifier normally generated by the sender's mail system. Its domain can hint at the originating platform.", "Message"],
  "references": ["Conversation references", "Identifiers of earlier emails used by mail clients to build a conversation thread.", "Message"],
  "in-reply-to": ["Reply reference", "The Message-ID of the email this message directly replies to.", "Message"],
  "mime-version": ["Message format version", "Declares use of MIME, the standard that allows attachments, HTML, and international text.", "Content"],
  "content-type": ["Body and attachment format", "Describes how the message body and its parts are structured and encoded.", "Content"],
  "content-language": ["Content language", "The language the sender's software associated with the message content.", "Content"],
  "x-ms-has-attach": ["Attachment indicator", "Microsoft's indicator that the message contains one or more attachments.", "Content"],
  "x-virus-scan": ["Malware scan result", "A vendor-specific record from a virus or malware scanning stage.", "Security signals"],
  "x-forefront-antispam-report": ["Microsoft spam assessment", "Microsoft's machine-readable spam report, including connecting IP, country, spam confidence, and disposition signals.", "Security signals"],
  "x-warn": ["Gateway warning", "A mail security gateway warning about a detected message characteristic or policy signal.", "Security signals"],
  "x-note": ["Gateway processing note", "A vendor-specific processing, scanning, or policy note. Useful for experts, but not part of the core email standard.", "Vendor diagnostics"]
};

const CATEGORY_TEXT = {
  "Identity": "Who the message says it is from and who it addresses.",
  "Authentication": "Evidence used to verify domains, servers, and forwarding history.",
  "Routing": "The server-to-server path and timing of delivery.",
  "Message": "Identifiers and display information created by the sender.",
  "Content": "How the body, language, and attachments are structured.",
  "Security signals": "Spam, malware, and policy decisions made by gateways.",
  "Vendor diagnostics": "Provider-specific operational data for deeper investigation.",
  "Other": "Additional technical metadata not covered by a standard category."
};

const state = { fields: [], hops: [], auth: {}, filter: "All", query: "", currentHop: 0 };
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value = "") => value.replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

function highlightValue(value) {
  const tokenPattern = /(\b[a-z][a-z0-9._-]*(?==))|([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})|(\b(?:\d{1,3}\.){3}\d{1,3}\b)|(\b(?:pass(?:ed)?|fail(?:ed)?|softfail|temperror|permerror)\b)|(\b(?:ESMTPS?|SMTP|MAPI|PIPE|TLS(?:v|_)?[\d_.]+)\b)|(\b(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun),?\s+\d{1,2}\s+[A-Z][a-z]{2}\s+\d{4}\s+\d{2}:\d{2}(?::\d{2})?\s+(?:[+-]\d{4}|UTC|GMT)\b)/gi;
  let html = "";
  let cursor = 0;
  for (const match of value.matchAll(tokenPattern)) {
    html += escapeHtml(value.slice(cursor, match.index));
    let className = "syntax-date";
    if (match[1]) className = "syntax-parameter";
    else if (match[2]) className = "syntax-email";
    else if (match[3]) className = "syntax-ip";
    else if (match[4]) className = /^pass/i.test(match[0]) ? "syntax-pass" : "syntax-fail";
    else if (match[5]) className = "syntax-protocol";
    html += `<span class="${className}">${escapeHtml(match[0])}</span>`;
    cursor = match.index + match[0].length;
  }
  return html + escapeHtml(value.slice(cursor));
}

function highlightHeader(raw) {
  return raw.split("\n").map(line => {
    const field = line.match(/^([^\s:][^:]*)(:)(.*)$/);
    if (!field) return highlightValue(line);
    return `<span class="syntax-field">${escapeHtml(field[1])}</span><span class="syntax-colon">:</span>${highlightValue(field[3])}`;
  }).join("\n");
}

function updateEditor() {
  const input = $("#headerInput");
  const lines = input.value ? input.value.split(/\r?\n/).length : 1;
  $("#highlightLayer").innerHTML = highlightHeader(input.value);
  $("#lineNumbers").textContent = Array.from({ length: lines }, (_, index) => index + 1).join("\n");
}

function syncEditorScroll() {
  const input = $("#headerInput");
  $("#highlightLayer").scrollTop = input.scrollTop;
  $("#highlightLayer").scrollLeft = input.scrollLeft;
  $("#lineNumbers").scrollTop = input.scrollTop;
}

function parseHeaders(raw) {
  const fields = [];
  const lines = raw.replace(/\r\n/g, "\n").split("\n");
  let current = null;
  lines.forEach((line, index) => {
    if (/^[ \t]/.test(line) && current) {
      current.value += " " + line.trim();
      current.raw += "\n" + line;
      return;
    }
    const match = line.match(/^([^\s:][^:]*):\s*(.*)$/);
    if (match) {
      current = { name: match[1].trim(), key: match[1].trim().toLowerCase(), value: match[2].trim(), raw: line, line: index + 1 };
      fields.push(current);
    } else if (line.trim()) {
      current = null;
    }
  });
  return fields.map(field => ({ ...field, ...describeField(field) }));
}

function describeField(field) {
  let info = FIELD_INFO[field.key];
  if (!info && field.key.startsWith("received")) info = FIELD_INFO.received;
  if (!info && field.key.startsWith("x-note")) info = FIELD_INFO["x-note"];
  if (!info && /^(x-ms|x-microsoft|x-forefront|x-eop|x-cloud|x-policy|x-primary|x-gbudb|x-signature|x-mlmodel)/.test(field.key)) {
    info = ["Provider-specific diagnostic", "Operational metadata added by a mail or security provider. It can help administrators investigate filtering and transport behavior.", "Vendor diagnostics"];
  }
  if (!info && /^(thread-|accept-language|x-mailbox-line)/.test(field.key)) info = ["Message client metadata", "Metadata added by the sender's mail application to support display, language, or conversation features.", "Message"];
  if (!info) info = [humanize(field.name), "An additional email metadata field. Its exact meaning depends on the system that added it.", "Other"];
  return { friendly: info[0], description: info[1], category: info[2] };
}

function humanize(name) {
  return name.replace(/^x-/i, "").split("-").map(word => word ? word[0].toUpperCase() + word.slice(1).toLowerCase() : "").join(" ");
}

function parseHop(field, index, total) {
  const value = field.value;
  const fromMatch = value.match(/\bfrom\s+([^\s(;,]+)/i);
  const byMatch = value.match(/\bby\s+([^\s(;,]+)/i);
  const ips = [...value.matchAll(/(?:\[)?((?:\d{1,3}\.){3}\d{1,3}|[a-f0-9]{0,4}:[a-f0-9:]+)(?:\])?/gi)].map(m => m[1]);
  const timePart = value.includes(";") ? value.slice(value.lastIndexOf(";") + 1).trim() : "";
  const parsedTime = Date.parse(timePart);
  const tls = value.match(/TLS(?:v|_)?[\d_.]+|ESMTPS?|SMTP|MAPI|PIPE/i);
  const cipher = value.match(/cipher=([A-Z0-9_]+)/i);
  const from = fromMatch?.[1] || (index === 0 ? "Origin system" : "Unidentified server");
  const by = byMatch?.[1] || (index === total - 1 ? "Destination system" : "Unidentified server");
  return { from, by, ips, time: Number.isNaN(parsedTime) ? null : new Date(parsedTime), timeRaw: timePart || "Not recorded", protocol: tls?.[0] || "Not stated", cipher: cipher?.[1] || null, secure: /TLS|ESMTPS/i.test(value), raw: field.value };
}

function identifyProvider(host) {
  const value = host.toLowerCase();
  if (/outlook|office365|microsoft|protection\.outlook|namprd/.test(value)) return "Microsoft 365";
  if (/appriver/.test(value)) return "AppRiver security gateway";
  if (/checkpoint|cloud-sec-av/.test(value)) return "Check Point cloud security";
  if (/google|gmail/.test(value)) return "Google Workspace";
  if (/amazonses|amazonaws/.test(value)) return "Amazon Web Services";
  if (/mimecast/.test(value)) return "Mimecast security gateway";
  if (/proofpoint/.test(value)) return "Proofpoint security gateway";
  if (/localhost|unidentified|origin|destination/.test(value)) return "Unidentified mail system";
  return "Independent mail system";
}

function classifyAddress(ip) {
  if (!ip) return "No IP address recorded";
  if (/^(10\.|127\.|192\.168\.|169\.254\.)/.test(ip) || /^172\.(1[6-9]|2\d|3[01])\./.test(ip) || /^(::1|f[cd]|fe80)/i.test(ip)) return "Private or internal address";
  if (ip.includes(":")) return "Public IPv6 address";
  return "Public IPv4 address";
}

function formatHopDelay(index) {
  if (index === 0) return "First recorded event";
  const previous = state.hops[index - 1].time;
  const current = state.hops[index].time;
  if (!previous || !current) return "Cannot calculate";
  const seconds = Math.round((current - previous) / 1000);
  if (seconds < 0) return `${Math.abs(seconds)} sec clock difference`;
  if (seconds < 60) return `${seconds} sec after prior hop`;
  return `${Math.floor(seconds / 60)}m ${seconds % 60}s after prior hop`;
}

function getAuth(fields) {
  const sources = fields.filter(f => /^(authentication-results|arc-authentication-results|x-ms-exchange-authentication-results)$/.test(f.key));
  const current = sources[0]?.value || "";
  const result = {};
  ["spf", "dkim", "dmarc", "arc"].forEach(type => {
    const match = current.match(new RegExp(`(?:^|[;\\s])${type}=(pass|fail|softfail|neutral|none|temperror|permerror)`, "i"));
    result[type] = match ? match[1].toLowerCase() : "none";
  });
  return result;
}

function resultCopy(type, status) {
  const text = {
    spf: ["Sending server", "Checks whether the connecting IP was approved by the envelope sender's domain."],
    dkim: ["Message signature", "Checks whether a domain signature is valid and signed content stayed intact."],
    dmarc: ["Domain alignment", "Checks that SPF or DKIM passes and aligns with the address shown in From."],
    arc: ["Forwarding history", "Checks whether authentication evidence preserved by forwarding systems is trustworthy."]
  }[type];
  const verdict = status === "pass" ? "Passed" : status === "none" ? "Not found" : status === "fail" ? "Failed" : humanize(status);
  return { title: text[0], description: text[1], verdict };
}

function formatDuration(hops) {
  const times = hops.map(h => h.time?.getTime()).filter(Boolean);
  if (times.length < 2) return "—";
  const seconds = Math.max(...times) / 1000 - Math.min(...times) / 1000;
  if (seconds < 60) return `${Math.round(seconds)} sec`;
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ${Math.round(seconds % 60)}s`;
  return `${Math.floor(seconds / 3600)}h ${Math.round((seconds % 3600) / 60)}m`;
}

function renderReport() {
  const from = state.fields.find(f => f.key === "from")?.value || "Unknown sender";
  const date = state.fields.find(f => f.key === "date")?.value;
  $("#reportSubtitle").textContent = `Analyzed ${state.fields.length} fields from ${from}${date ? ` · ${date}` : ""}`;
  $("#hopCount").textContent = state.hops.length;
  $("#travelTime").textContent = formatDuration(state.hops);
  $("#fieldCount").textContent = state.fields.length;
  renderVerdict();
  renderAuth();
  renderRoute();
  renderFilters();
  renderFields();
}

function renderVerdict() {
  const failed = Object.entries(state.auth).filter(([, value]) => value === "fail").map(([key]) => key.toUpperCase());
  const passed = Object.values(state.auth).filter(value => value === "pass").length;
  const card = $("#verdictCard");
  card.className = "verdict-card " + (failed.length ? "danger" : passed >= 2 ? "safe" : "caution");
  $("#verdictIcon").textContent = failed.length ? "!" : passed >= 2 ? "✓" : "?";
  $("#verdictTitle").textContent = failed.length ? "Authentication concerns found" : passed >= 2 ? "Key checks passed" : "Limited trust evidence";
  $("#verdictText").textContent = failed.length ? `${failed.join(", ")} failed in the latest recorded results. Review the route and forwarding context.` : passed >= 2 ? "The latest recorded sender checks support the message's identity." : "There is not enough current authentication data for a strong conclusion.";
}

function renderAuth() {
  $("#authGrid").innerHTML = Object.entries(state.auth).map(([type, status]) => {
    const copy = resultCopy(type, status);
    const cls = status === "pass" ? "pass" : status === "fail" ? "fail" : "neutral";
    return `<article class="auth-item"><div class="auth-top"><span class="auth-name">${type.toUpperCase()}</span><span class="pill ${cls}">${copy.verdict}</span></div><h3>${copy.title}</h3><p>${copy.description}</p></article>`;
  }).join("");
}

function renderRoute() {
  const track = $("#routeTrack");
  if (!state.hops.length) {
    track.innerHTML = `<p class="empty-state">No valid Received headers were found, so a route cannot be reconstructed.</p>`;
    return;
  }
  track.innerHTML = state.hops.map((hop, index) => `<button class="route-node" data-hop="${index}" type="button" aria-label="Open details for hop ${index + 1}, ${escapeHtml(hop.from)}"><span class="node-dot">${String(index + 1).padStart(2, "0")}</span><h3 title="${escapeHtml(hop.from)}">${escapeHtml(shortHost(hop.from))}</h3><p>${hop.time ? hop.time.toLocaleTimeString([], {hour: "2-digit", minute: "2-digit", second: "2-digit"}) : hop.protocol}</p><span class="node-role">${escapeHtml(index === 0 ? "Origin" : index === state.hops.length - 1 ? "Final handoff" : hop.secure ? "Encrypted" : "Mail relay")}</span></button>`).join("");
  track.querySelectorAll(".route-node").forEach(button => button.addEventListener("click", () => showHop(Number(button.dataset.hop))));
}

function shortHost(host) {
  const parts = host.replace(/[\[\]]/g, "").split(".");
  return parts.length > 3 ? `${parts[0]}.${parts.slice(-2).join(".")}` : host;
}

function showHop(index) {
  const hop = state.hops[index];
  state.currentHop = index;
  document.querySelectorAll(".route-node").forEach((node, i) => node.classList.toggle("active", i === index));
  const provider = identifyProvider(hop.from);
  const addressType = classifyAddress(hop.ips[0]);
  const transportText = hop.secure ? `The handoff was encrypted using ${hop.protocol}${hop.cipher ? ` with ${hop.cipher}` : ""}.` : `No explicit TLS encryption was recorded for this handoff; the stated transport is ${hop.protocol}.`;
  $("#hopDialogStep").textContent = `DELIVERY HOP ${index + 1} OF ${state.hops.length}`;
  $("#hopDialogTitle").textContent = shortHost(hop.from);
  $("#hopDialogContent").innerHTML = `<div class="hop-overview"><div class="hop-status-row"><span class="hop-status ${hop.secure ? "secure" : "warning"}">${hop.secure ? "Encrypted transport" : "Encryption not stated"}</span><span class="hop-status">${escapeHtml(provider)}</span><span class="hop-status">${escapeHtml(addressType)}</span></div><p class="hop-explanation">At this step, <strong>${escapeHtml(hop.from)}</strong> handed the email to <strong>${escapeHtml(hop.by)}</strong>. ${escapeHtml(transportText)} This record was written by the receiving server, so it describes the handoff immediately before it.</p><div class="hop-journey"><div class="hop-endpoint"><small>Sending server</small><strong>${escapeHtml(hop.from)}</strong><span>${escapeHtml(hop.ips.join(", ") || "IP not recorded")}</span></div><div class="hop-arrow">→</div><div class="hop-endpoint"><small>Receiving server</small><strong>${escapeHtml(hop.by)}</strong><span>${escapeHtml(identifyProvider(hop.by))}</span></div></div><div class="hop-facts"><div class="hop-fact"><small>Recorded time</small><strong>${escapeHtml(hop.time ? hop.time.toLocaleString([], { dateStyle: "medium", timeStyle: "long" }) : hop.timeRaw)}</strong></div><div class="hop-fact"><small>Time since prior hop</small><strong>${escapeHtml(formatHopDelay(index))}</strong></div><div class="hop-fact"><small>Transport security</small><strong>${escapeHtml(hop.secure ? `${hop.protocol}${hop.cipher ? ` · ${hop.cipher}` : ""}` : hop.protocol)}</strong></div><div class="hop-fact"><small>Network address</small><strong>${escapeHtml(addressType)}</strong></div></div><div class="hop-evidence"><h3>Original Received evidence</h3><p>The exact normalized value parsed from this header.</p><p class="raw-value">${highlightValue(hop.raw)}</p></div></div>`;
  $("#hopPosition").textContent = `${index + 1} / ${state.hops.length}`;
  $("#previousHop").disabled = index === 0;
  $("#nextHop").disabled = index === state.hops.length - 1;
  const dialog = $("#hopDialog");
  if (!dialog.open) {
    if (typeof dialog.showModal === "function") dialog.showModal();
    else {
      dialog.setAttribute("open", "");
      dialog.classList.add("fallback-open");
    }
  }
}

function closeHopDialog() {
  const dialog = $("#hopDialog");
  if (typeof dialog.close === "function") dialog.close();
  else {
    dialog.removeAttribute("open");
    dialog.classList.remove("fallback-open");
  }
}

function renderFilters() {
  const categories = [...new Set(state.fields.map(field => field.category))];
  $("#filterRow").innerHTML = ["All", ...categories].map(category => `<button class="filter-button ${state.filter === category ? "active" : ""}" data-filter="${escapeHtml(category)}" type="button">${escapeHtml(category)} <span>${category === "All" ? state.fields.length : state.fields.filter(f => f.category === category).length}</span></button>`).join("");
  $("#filterRow").querySelectorAll("button").forEach(button => button.addEventListener("click", () => { state.filter = button.dataset.filter; renderFilters(); renderFields(); }));
}

function renderFields() {
  const query = state.query.toLowerCase();
  const filtered = state.fields.filter(field => (state.filter === "All" || field.category === state.filter) && (!query || `${field.name} ${field.value} ${field.friendly} ${field.description}`.toLowerCase().includes(query)));
  const grouped = Object.values(filtered.reduce((groups, field) => {
    const key = `${field.key}|${field.category}`;
    if (!groups[key]) groups[key] = { ...field, values: [] };
    groups[key].values.push(field);
    return groups;
  }, {}));
  $("#emptyState").classList.toggle("hidden", grouped.length > 0);
  $("#fieldList").innerHTML = grouped.map((group, index) => {
    const joined = group.values.map(v => v.value).join(" · ");
    const valuesHtml = group.values.map((value, valueIndex) => `<p class="raw-value">${group.values.length > 1 ? `<b>Occurrence ${valueIndex + 1}</b><br>` : ""}${highlightValue(value.value)}</p>`).join("<br>");
    return `<article class="field-item"><button class="field-button" type="button" aria-expanded="false"><span class="field-title"><code>${escapeHtml(group.name)}${group.values.length > 1 ? ` × ${group.values.length}` : ""}</code><strong>${escapeHtml(group.friendly)}</strong></span><span class="field-preview">${highlightValue(joined)}</span><span class="chevron">⌄</span></button><div class="field-body"><p class="explanation">${escapeHtml(group.description)}</p>${valuesHtml}<div class="field-meta">${escapeHtml(group.category)} · First appears on line ${group.line}</div></div></article>`;
  }).join("");
  $("#fieldList").querySelectorAll(".field-button").forEach(button => button.addEventListener("click", () => {
    const item = button.closest(".field-item");
    item.classList.toggle("open");
    button.setAttribute("aria-expanded", item.classList.contains("open"));
  }));
  const category = state.filter === "All" ? "All fields" : state.filter;
  $("#categorySummary").innerHTML = `<h3>${escapeHtml(category)}</h3><p>${state.filter === "All" ? "A complete inventory of the standards-based and provider-specific metadata in this message." : escapeHtml(CATEGORY_TEXT[state.filter] || CATEGORY_TEXT.Other)}</p><strong>${filtered.length}</strong><small>matching sections</small>`;
}

function analyze() {
  const raw = $("#headerInput").value.trim();
  const fields = parseHeaders(raw);
  if (!raw || fields.length < 2) {
    $("#inputError").textContent = "Paste a raw header containing at least two valid Name: value fields.";
    return;
  }
  $("#inputError").textContent = "";
  state.fields = fields;
  const received = fields.filter(field => field.key === "received");
  state.hops = received.slice().reverse().map((field, index) => parseHop(field, index, received.length));
  state.auth = getAuth(fields);
  state.filter = "All";
  state.query = "";
  $("#fieldSearch").value = "";
  renderReport();
  $("#inputSection").classList.add("hidden");
  $("#reportSection").classList.remove("hidden");
  window.scrollTo({ top: 0, behavior: "smooth" });
}

async function loadSample() {
  const button = $("#sampleButton");
  button.disabled = true;
  button.textContent = "Loading example…";
  try {
    const response = await fetch("header-example.txt");
    if (!response.ok) throw new Error("Unable to load example");
    $("#headerInput").value = await response.text();
    updateLineCount();
    analyze();
  } catch {
    $("#inputError").textContent = "The example can be loaded when the site is served over HTTP (not opened as a local file).";
  } finally {
    button.disabled = false;
    button.textContent = "Use example header";
  }
}

function updateLineCount() {
  const value = $("#headerInput").value;
  const count = value ? value.split(/\r?\n/).length : 0;
  $("#lineCount").textContent = `${count} line${count === 1 ? "" : "s"}`;
  updateEditor();
}

function reset() {
  $("#reportSection").classList.add("hidden");
  $("#inputSection").classList.remove("hidden");
  setTimeout(() => $("#headerInput").focus(), 100);
}

function copySummary() {
  const failed = Object.entries(state.auth).filter(([, value]) => value === "fail").map(([key]) => key.toUpperCase());
  const summary = `TraceMail email header summary\nSender: ${state.fields.find(f => f.key === "from")?.value || "Unknown"}\nServer hops: ${state.hops.length}\nTravel time: ${formatDuration(state.hops)}\nAuthentication: ${Object.entries(state.auth).map(([key, value]) => `${key.toUpperCase()} ${value}`).join(", ")}\nAssessment: ${failed.length ? `${failed.join(", ")} failed in latest results` : "No failures in latest recorded results"}`;
  navigator.clipboard.writeText(summary).then(() => {
    $("#copySummaryButton").textContent = "Copied";
    setTimeout(() => $("#copySummaryButton").textContent = "Copy summary", 1600);
  });
}

$("#headerInput").addEventListener("input", updateLineCount);
$("#headerInput").addEventListener("scroll", syncEditorScroll);
$("#headerInput").addEventListener("keydown", event => {
  if (event.key !== "Tab") return;
  event.preventDefault();
  const input = event.currentTarget;
  const start = input.selectionStart;
  input.setRangeText("  ", start, input.selectionEnd, "end");
  updateLineCount();
});
$("#analyzeButton").addEventListener("click", analyze);
$("#sampleButton").addEventListener("click", loadSample);
$("#newAnalysisButton").addEventListener("click", reset);
$("#copySummaryButton").addEventListener("click", copySummary);
$("#fieldSearch").addEventListener("input", event => { state.query = event.target.value; renderFields(); });
$("#routeLeft").addEventListener("click", () => $("#routeScroll").scrollBy({left: -380, behavior: "smooth"}));
$("#routeRight").addEventListener("click", () => $("#routeScroll").scrollBy({left: 380, behavior: "smooth"}));
$("#hopDialogClose").addEventListener("click", closeHopDialog);
$("#previousHop").addEventListener("click", () => showHop(state.currentHop - 1));
$("#nextHop").addEventListener("click", () => showHop(state.currentHop + 1));
$("#hopDialog").addEventListener("click", event => {
  if (event.target === event.currentTarget) closeHopDialog();
});

const routeScroll = $("#routeScroll");
let drag = null;
routeScroll.addEventListener("pointerdown", event => { drag = { x: event.clientX, left: routeScroll.scrollLeft, pointerId: event.pointerId, moved: false }; });
routeScroll.addEventListener("pointermove", event => {
  if (!drag) return;
  const distance = event.clientX - drag.x;
  if (!drag.moved && Math.abs(distance) < 6) return;
  if (!drag.moved) {
    drag.moved = true;
    routeScroll.classList.add("dragging");
    routeScroll.setPointerCapture(drag.pointerId);
  }
  routeScroll.scrollLeft = drag.left - distance;
});
routeScroll.addEventListener("pointerup", event => {
  if (drag?.moved) event.preventDefault();
  drag = null;
  routeScroll.classList.remove("dragging");
});
routeScroll.addEventListener("pointercancel", () => { drag = null; routeScroll.classList.remove("dragging"); });

const editorResizeObserver = new ResizeObserver(entries => {
  const height = entries[0].target.offsetHeight;
  $("#highlightLayer").style.height = `${height}px`;
  $("#lineNumbers").style.height = `${height}px`;
});
editorResizeObserver.observe($("#headerInput"));
updateEditor();
